/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    DirectoryTree: typeof import('./src/components/DirectoryTree.vue')['default']
    ErrorRecoveryMonitor: typeof import('./src/components/ErrorRecoveryMonitor.vue')['default']
    MigrationDialog: typeof import('./src/components/MigrationDialog.vue')['default']
    OperationLogViewer: typeof import('./src/components/OperationLogViewer.vue')['default']
    PerformanceMonitor: typeof import('./src/components/PerformanceMonitor.vue')['default']
    TestManager: typeof import('./src/components/TestManager.vue')['default']
  }
}
